In [1]:
import numpy as np
a=np.array([5,6,7])

In [2]:
a

array([5, 6, 7])

In [3]:
a.ndim

1

In [4]:
a[0]

5

In [5]:
a[2]

7

In [7]:
a=np.array([[1,2],[3,4],[5,6]])

In [8]:
a.ndim

2

In [9]:
a.itemsize

4

In [18]:
a.dtype

dtype('complex128')

In [19]:
a=np.array([[1,2],[3,4],[5,6]],dtype=np.float64)

In [21]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [22]:
a.size

6

In [23]:
a.shape

(3, 2)

In [24]:
a=np.array([[1,2],[3,4],[5,6]],dtype=np.complex)

In [25]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [26]:
a.dtype

dtype('complex128')

In [27]:
a=np.zeros((3,4))

In [28]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
a=np.ones((3,4))

In [30]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
l=range(5)

In [32]:
l

range(0, 5)

In [33]:
l[0]

0

In [34]:
l[3]

3

In [35]:
a=np.arange(1,5)

In [36]:
a

array([1, 2, 3, 4])

In [37]:
np.arange(1,9,2)

array([1, 3, 5, 7])

In [38]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [39]:
a=np.array([[1,2],[3,4],[5,6]])

In [40]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
a.shape

(3, 2)

In [42]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [44]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [45]:
a.min()

1

In [46]:
a.max()

6

In [47]:
a.sum()

21

In [48]:
a.sum(axis=0)

array([ 9, 12])

In [49]:
a.sum(axis=1)

array([ 3,  7, 11])

In [51]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [52]:
np.std(a)

1.707825127659933

In [53]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [54]:
a

array([[1, 2],
       [3, 4]])

In [55]:
b

array([[5, 6],
       [7, 8]])

In [56]:
a+b

array([[ 6,  8],
       [10, 12]])

In [57]:
a-b

array([[-4, -4],
       [-4, -4]])

In [58]:
a*b

array([[ 5, 12],
       [21, 32]])

In [59]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [60]:
a.dot(b)

array([[19, 22],
       [43, 50]])