In [1]:
import numpy as np
a=np.array([1,2,3])

In [2]:
a

array([1, 2, 3])

In [3]:
a[0]

1

In [4]:
a[2]

3

In [10]:
import sys

In [11]:
x=range(500)

In [12]:
array=np.arange(500)

In [13]:
print(sys.getsizeof(5)*len(x))
print(array.size*array.itemsize)

14000
2000


In [14]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])


In [15]:
a1+a2

array([5, 7, 9])

In [16]:
a1-a2

array([-3, -3, -3])

In [17]:
a1*a2

array([ 4, 10, 18])

In [18]:
a1/a2

array([0.25, 0.4 , 0.5 ])